<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="vos.ManagedMicroservice.Metabolism.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\vos.Auth.Shared\vos.Auth.Shared.csproj" />
    <ProjectReference Include="..\vos.ManagedMicroservice.Shared\vos.ManagedMicroservice.Shared.csproj" />
  </ItemGroup>

</Project>
